name: Exceso_mortalidad
on:
  workflow_dispatch:
  schedule:
    - cron:  '21 20 * * *'

jobs:
  Exceso_mortalidad:
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out our repo'
      uses: actions/checkout@v2
      with:
          path: Datos-COVID19
   
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        cd Datos-COVID19/src
        Rscript exceso_mortalidad.R
      
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: "Added data from DEIS - Exceso Mortalidad to repo"
        repository: Datos-COVID19
        commit_user_name: MinCiencia GitHub Actions Bot
        commit_user_email: actions@github.com
        commit_author: minciencia github bot <actions@github.com>
