name: Exceso_mortalidad
on:
  workflow_dispatch:
  schedule:
    - cron:  '21 20 * * *'

jobs:
  Exceso_mortalidad:
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out our repo'
      uses: actions/checkout@v2
      with:
          path: Datos-COVID19
   
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        R -e 'install.packages("httr")'
        R -e 'install.packages("visreg")'
        R -e 'install.packages("ggplot2")'
        R -e 'install.packages("mgcv")'
        R -e 'install.packages("MASS")'
        R -e 'install.packages("lubridate")'
        R -e 'install.packages("tidyr")'
        R -e 'install.packages("dplyr")'
        R -e 'install.packages("readr")'
        
    - name: Generar productos
      run: |
          cd Datos-COVID19/src
          Rscript exceso_mortalidad.R
          
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: "Added data from DEIS - Exceso Mortalidad to repo"
        repository: Datos-COVID19
        commit_user_name: MinCiencia GitHub Actions Bot
        commit_user_email: actions@github.com
        commit_author: minciencia github bot <actions@github.com>
